In [2]:
import numpy

In [3]:
n = numpy.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [8]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [10]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
m = numpy.asarray([[123,12,123,12,33],[],[]], dtype=object)
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [17]:
import cv2

In [18]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
im_c = cv2.imread("smallgray.png", 1)

In [21]:
im_c

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [23]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [26]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [30]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [32]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [34]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [46]:
imh = numpy.hstack((im_g, im_g))

In [47]:
imh

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [44]:
imv = numpy.vstack((im_g, im_g))

In [48]:
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [55]:
hlst = numpy.hsplit(imh, 5)
hlst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8),
 array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8),
 array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [57]:
vlst = numpy.vsplit(imv, 2)
vlst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]